export default {
  about: "/src/assets/images/Rectangle15.png",
  vector: "/src/assets/images/Vector (3).png",
  vector2: "/src/assets/images/Vector (5).png",
  globalImg: "/src/assets/Vector (2).png",
  graph: "/src/assets/images/ic-trending-up-24px (1).png",
  arrow: "/src/assets/images/mage_goals-fill.png",
  vector4: "/src/assets/images/Group 1171275311.png",
  coloredVector: "/src/assets/images/Vector (8).png",
  call: "/src/assets/images/call1.png",
  whatsapp: "/src/assets/images/whatsapp.png",
  logo2: "/src/assets/images/Rectangle 1.png",
  facebook: "/src/assets/images/Vector (9).png",
  X: "/src/assets/images/Group.png",
  insta: "/src/assets/images/instagram (2) 1.png",
  snap: "/src/assets/images/snapchat (1) 1.png",
  tiktok: "/src/assets/images/Vector (10).png",
  youtube: "/src/assets/images/Vector (11).png",
  apple: "/src/assets/images/appStore.jpg",
  sms: "/src/assets/images/sms1.png",
  calender: "/src/assets/Vector.png",
  clockImg: "/src/assets/Vector (1).png",
  Logo: "/src/assets/images/Rectangle 1 (1).png",
  KSAFlag: "/src/assets/image.png",
  light: "/src/assets/images/flat-color-icons_idea.png",
  game: "/src/assets/images/game-icons_road.png",
  vector3: "/src/assets/images/Vector (6).png",
  googlePly: "/src/assets/images/GooglePlay.jpg",
  callFooter: "/src/assets/images/call.png",
  smsFooter: "/src/assets/images/sms.png",
};
